### ISSUE TITLE
Move Rfc7230 to a Http1 sub-namespace

### ISSUE THREAD

**Issue by leonardocustodio** [amphp/http#21]
This commit requires change on `http-client` we get the following error after the PR was merged:

Process exited with an uncaught exception: Error thrown in context with message "Class "Amp\Http\Rfc7230" not found" and code "0" in /home/custodio/Development/Enjin/open-platform-core/vendor/amphp/http-client/src/Connection/Http1Connection.php:670; call Amp\Parallel\Context\ContextPanicError::getOriginalTrace() for the stack trace in the context as an array; if the Xdebug extension is enabled, set "xdebug.mode" to "debug" to include the exception stack trace in the context in the exception message

**Comment by kelunik** [comment]
Yes, we're aware. Please use the tagged beta versions in the meantime.
